spring.application.name=expense-management-system



#configuration for database connection

spring.datasource.url=jdbc:postgresql://localhost:5433/expense_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver




spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

server.port=8081